### ISSUE TITLE
Cam 사용 버젼

### ISSUE THREAD

**Issue by yjhong89** [bobhyun/TS-ANPR#2]
안녕하세요, Web cam 을 이용해서 streaming 식으로 ANPR 엔진을 사용해보고 싶은데, 혹시 가이드라인이 있을까요??

감사합니다.

**Comment by bobhyun** [comment]
안녕하세요.

웹캠으로 차번 인식하는 방법을 문의하시는 분들이 많아서 파이썬 예제를 올렸습니다.
https://github.com/bobhyun/TS-ANPR/blob/main/examples/python/anprWebcam.py

도움 되시기 바랍니다.

**Comment by yjhong89** [comment]
답변 감사합니다!
