### ISSUE TITLE
전기차 번호판 검출 관련 문의

### ISSUE THREAD

**Issue by ilwoonam75** [bobhyun/TS-ANPR#7]
안녕하세요.

다수개 (6개 이상)의 차량을 모니터링하고 있는 CCTV 화면에서 전기차 번호판과 일반 번호판을 구분할 수 있을까요?

**Comment by bobhyun** [comment]
안녕하세요.
답변이 늦어져 죄송합니다.
차량 수는 기술적으로 제약 사항이 아니지만 촬영된 각 번호판의 품질과 크기에 영향을 받을 수 있습니다.
샘플 이미지를 몇 장 보내주시면 검토해서 구체적인 답변 드리겠습니다.

**Comment by ilwoonam75** [comment]
안녕하세요.
답변 감사드립니다

이미지를 제공해드리고 싶지만 보안 이슈 때문에 제공 드리기는 어려운 점 양해 부탁드립니다.

다만 영상은 현재 github에 보여주고 계시는 어안 카메라와 비슷한 느낌이구요. 
카메라 해상도는 4000x3000을 사용하고 있습니다.

**Comment by bobhyun** [comment]
잘 알겠습니다.

동일한 해상도의 카메라라도 튜닝이 조금 씩 다를 수 있기 때문에
가능하시면 [😍 차번 인식 라이브 데모](http://tsnvr.ipdisk.co.kr/) 사이트에서 직접 테스트해 보시기 바랍니다.

지하 주차장 6면(또는 12면)용 어안 카메라의 경우 
저희 차번 인식 알고리즘으로는 전기차 여부를 판단하기 어려울 수 있습니다.

현재 알고리즘은 주변 조도의 영향을 받지 않고 특히 야간 IR카메라(흑백이미지)에도 사용할 수 있도록
번호판 배경색을 인식하는 방식 대신 번호판의 전기차 로고를 인식하는 방식을 사용하고 있습니다.
![image](https://github.com/user-attachments/assets/67d32f4c-bb8a-4bfd-bfcf-ef23698e8c09)
`[이미지 출처] 네이버 포스트 https://post.naver.com/viewer/postView.nhn?volumeNo=17519067&memberNo=30619985`

아래 이미지는 유사한 사양의 4000x3000 해상도 카메라로 촬영된 
전기차 번호판 (원본 이미지 크기)인데 좌우측 전기차 로고 부분이 거의 식별이 안됩니다. 
![image](https://github.com/user-attachments/assets/e78ce4b2-a1ef-457d-b3e8-f35bd0734d04)
`[개인정보 보호를 위해 차량번호 일부분은 마스킹 했습니다.]`

이와 유사한 품질의 이미지에서는 전기차 로고 인식이 어려워 보이고
제한적이지만 번호판 배경색 인식 방식이 차선책이 될 수도 있겠습니다.

하지만 근본적으로 차량 번호판에서 얻을 수 있는 정보만으로는 전기차 여부를 완벽히 판단할 수 없습니다.
[국토교통부 번호판 규격](https://www.molit.go.kr/USR/I0204/m_45/dtl.jsp?gubun=4&search=&search_dept_id=&search_dept_nm=&old_search_dept_nm=&psize=10&search_regdate_s=&search_regdate_e=&srch_usr_nm=&srch_usr_num=&srch_usr_year=&srch_usr_titl=&srch_usr_ctnt=&lcmspage=3&idx=16757)에 의하면 영업용 차량의 경우 내연기관, 전기차 구분없이 동일한 규격으로 되어 있습니다.

이런 이유 때문에 지하주차장에 주차된 택시의 경우 차량 번호판으로 전기차 여부를 판단할 근거가 없습니다.

이 답변이 도움이 되셨기를 바랍니다.
감사합니다.

**Comment by ilwoonam75** [comment]
상세한 답변 감사드립니다. 
말씀해주신 것처럼 테스트 진행해보겠습니다.
다시 한번 감사드립니다.
